#!/bin/sh
# Set up default values which will be overwritten if they exist in /etc/clearwater/config
hss_hostname="0.0.0.0"
hss_port=3868
homestead_provisioning_port=8889
homestead_password_encryption_key="2lB6HWYd1cvuGbAdey9cFL5bSWDzxHOsYyPLYOxV3Bs"
cassandra_hostname="localhost"
. /etc/clearwater/config

# Work out what features are enabled.
LOCAL_PROVISIONING_ENABLED=Y
if [ -d /etc/clearwater/features.d ]
then
  for file in $(find /etc/clearwater/features.d -type f)
  do
    [ -r $file ] && . $file
  done
fi

case "$LOCAL_PROVISIONING_ENABLED" in
  Y) local_prov_setting=True ;;
  *) local_prov_setting=False ;;
esac

# Legacy configuration may have a port numbers - strip it.  Note that IPv6
# "hostnames" will not have port numbers appended, so we just pass those on
# verbatim by detecting 2 or more colons.
hs_hostname=$(echo $hs_hostname | sed -e 's/^\([^:]*\):[0-9][0-9]*$/\1/g')
sed -e 's/^LOCAL_IP = .*$/LOCAL_IP = "'$local_ip'"/g
        s/^SIP_DIGEST_REALM = .*$/SIP_DIGEST_REALM = "'$home_domain'"/g
        s/^SPROUT_HOSTNAME = .*$/SPROUT_HOSTNAME = "'$sprout_hostname'"/g
        s/^PUBLIC_HOSTNAME = .*$/PUBLIC_HOSTNAME = "'$public_hostname'"/g
        s/^HS_HOSTNAME = .*$/HS_HOSTNAME = "'$hs_hostname'"/g
        s/^HTTP_PORT = .*$/HTTP_PORT = '$homestead_provisioning_port'/g
        s/^PASSWORD_ENCRYPTION_KEY = .*$/PASSWORD_ENCRYPTION_KEY = "'$homestead_password_encryption_key'"/g
        s/^LOCAL_PROVISIONING_ENABLED = .*$/LOCAL_PROVISIONING_ENABLED = '$local_prov_setting'/g
        s/^CASS_HOST = .*$/CASS_HOST = "'$cassandra_hostname'"/g
        s/^CCF = .*$/CCF = "'$cdf_identity'"/g' \
            </usr/share/clearwater/homestead/src/metaswitch/crest/local_settings.py >/tmp/local_settings.py.$$

for dst in /usr/share/clearwater/homestead/src/metaswitch/crest/local_settings.py \
           /usr/share/clearwater/homestead/env/lib/python2.7/site-packages/crest-0.1-py2.7.egg/metaswitch/crest/local_settings.py
do
  if [ -f $dst ]
  then
    cp /tmp/local_settings.py.$$ $dst
  fi
done
rm /tmp/local_settings.py.$$
