#!/bin/sh
# Set up default values which will be overwritten if they exist in /etc/clearwater/config
hss_hostname="0.0.0.0"
hss_port=3868
homestead_password_encryption_key="2lB6HWYd1cvuGbAdey9cFL5bSWDzxHOsYyPLYOxV3Bs"
cassandra_hostname="localhost"
. /etc/clearwater/config
# Legacy configuration may have a port numbers - strip it.  Note that IPv6 
# "hostnames" will not have port numbers appended, so we just pass those on
# verbatim by detecting 2 or more colons.
hs_hostname=$(echo $hs_hostname | sed -e 's/^\([^:]*\):[0-9][0-9]*$/\1/g')
sed -e 's/^SIP_DIGEST_REALM = .*$/SIP_DIGEST_REALM = "'$home_domain'"/g
        s/^SPROUT_HOSTNAME = .*$/SPROUT_HOSTNAME = "'$sprout_hostname'"/g
        s/^PUBLIC_HOSTNAME = .*$/PUBLIC_HOSTNAME = "'$public_hostname'"/g
        s/^HS_HOSTNAME = .*$/HS_HOSTNAME = "'$hs_hostname'"/g
        s/^HSS_IP = .*$/HSS_IP = "'$hss_hostname'"/g
        s/^HSS_PORT = .*$/HSS_PORT = '$hss_port'/g
        s/^PASSWORD_ENCRYPTION_KEY = .*$/PASSWORD_ENCRYPTION_KEY = "'$homestead_password_encryption_key'"/g
        s/^CASS_HOST = .*$/CASS_HOST = "'$cassandra_hostname'"/g' </usr/share/clearwater/homestead/src/metaswitch/crest/local_settings.py >/tmp/local_settings.py.$$
for dst in /usr/share/clearwater/homestead/src/metaswitch/crest/local_settings.py \
           /usr/share/clearwater/homestead/env/lib/python2.7/site-packages/crest-0.1-py2.7.egg/metaswitch/crest/local_settings.py
do
  if [ -f $dst ]
  then
    cp /tmp/local_settings.py.$$ $dst
  fi
done
rm /tmp/local_settings.py.$$

if [ $(dpkg-query -W -f='${PackageSpec}\n' | egrep '^(bono|ellis|homer|homestead|sprout)$' | wc -l) -eq 5 ] &&
     grep 'half_system_memory_in_mb="1024"' /etc/cassandra/cassandra-env.sh > /dev/null
  then
  sed -i 's/"$half_system_memory_in_mb" -gt "1024"/"$half_system_memory_in_mb" -gt "256"/' /etc/cassandra/cassandra-env.sh
  sed -i 's/half_system_memory_in_mb="1024"/half_system_memory_in_mb="256"/' /etc/cassandra/cassandra-env.sh
  service cassandra restart
  sleep 30 # Wait for Cassandra to reactivate
fi
